
config:
  user-name: demo4
  region: us-east-1
  bucket-name: sagemaker-ml-pipeline-demo4-20220708-214303
  s3-prefix: sagemaker/sagemaker-ml-pipeline/demo4
  num-of-segment: 2
  codepipeline-name: sagemaker-ml-pipeline-ml-codepipeliune-demo4
  prep-image-name: sagemaker-ml-pipeline-prep-demo4
  train-image-name: sagemaker-ml-pipeline-train-demo4
  sfn-workflow-arn: arn:aws:states:us-east-1:598610803365:stateMachine:sagemaker-ml-pipeline-demo4
  sfn-role-arn: arn:aws:iam::598610803365:role/service-role/sagemaker-ml-pipeline-stepfunctions-demo4-role
  sagemaker-role: arn:aws:iam::598610803365:role/service-role/AmazonSageMaker-ExecutionRole-20220708T094454
  notification-lambda-name: sagemaker-ml-pipeline-notification-demo4
  sns-topic-arn: arn:aws:sns:us-east-1:598610803365:sagemaker-ml-pipeline-notification-demo4
